# Alacritty Configuration for Windows WSL
# Installation:
# 1. Create directory: C:\Users\<USERNAME>\AppData\Roaming\alacritty\
# 2. Copy this file to: C:\Users\<USERNAME>\AppData\Roaming\alacritty\alacritty.toml
# 3. Create theme directory: C:\Users\<USERNAME>\AppData\Roaming\alacritty\themes\themes\
# 4. Copy ayu_dark.toml to: C:\Users\<USERNAME>\AppData\Roaming\alacritty\themes\themes\ayu_dark.toml
#
# WSL Dependencies:
# - Zellij should be installed via cargo: cargo install zellij
# - FiraCode Nerd Font should be installed in Windows
# - Make sure ~/.cargo/bin is in your PATH in WSL

[general]
import = [
  "./themes/themes/ayu_dark.toml"
]

[window]
padding = { x = 16, y = 14 }
decorations = "full"

[font]
size = 13

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[terminal.shell]
program = "C:\\Windows\\System32\\wsl.exe"
args = [
  "~",
  "-d",
  "Ubuntu",
  "-e",
  "/home/nh/.cargo/bin/zellij",
  "attach",
  "-c"
]

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"
