import = [
  "~/.config/alacritty/themes/themes/ayu_dark.toml"
]

[window]
padding.x = 16
padding.y = 14
decorations = "none" # Removes the window decoration (title bar, etc.)

[font]
size = 13

# FiraCode Nerd Font
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }

[shell]
  program = "/bin/zsh"
  args = ["-l", "-c", "zellij"]
